language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python -m pytest -v --cov ath --cov-report term-missing
after_success:
- coveralls
notifications:
  email: false
  